### ISSUE TITLE
Handle deletion cascading

### ISSUE THREAD

**Issue by Riari** [AndreasElia/laravel-firefly#153]
We need to implement deletion cascading for discussions and groups. I think we have two options for handling this:

- Handle all cascading via Eloquent events
- Use native SQL cascades for "hard deletes" and use Eloquent events specifically for soft deletes

I think the extra performance of the second option is probably worth the extra bit of effort to implement, but I'll leave this alone for a few days to get feedback before I start doing anything with it.

**Comment by ConnorVG** [comment]
This also comes down to database support – not all databases support foreign key constraints (or at-least delete cascading like Mongo).

It would make sense, in this note (with it being a generic package), to instead handle it in the application rather than depend on the database. Or, at-least, offer it as optional behaviour if you do want to utilise foreign key constraints.

**Comment by AndreasElia** [comment]
Handled in the database for now, will (hopefully) change in the future PR.
